-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg8MKIbydVds4pF+xo
m6PojerBCVOtqNsfJhfo7yEY7IGgCgYIKoZIzj0DAQehRANCAARummVxVEh6Vyzk
9/YL5KH933/eW06pNteEJqed5fWc/QJpyt71lq1WH+6Y/1QfCqNSeb/DIBxfhUdi
CGaputRJ
-----END PRIVATE KEY-----